// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAryY_RPbo_yh5z4V79i3Iz4eKI22F01_0',
    appId: '1:105947681683:web:d784df15a256db30c80e66',
    messagingSenderId: '105947681683',
    projectId: 'career-guidance-app-98f12',
    authDomain: 'career-guidance-app-98f12.firebaseapp.com',
    storageBucket: 'career-guidance-app-98f12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdqNKzu7k3AjwsrSDxDhLBKS0ofqXk7jY',
    appId: '1:105947681683:android:498e3a1d8099e7a7c80e66',
    messagingSenderId: '105947681683',
    projectId: 'career-guidance-app-98f12',
    storageBucket: 'career-guidance-app-98f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu4il-68xX38EfTSR_Eati6kypYbXqnMQ',
    appId: '1:105947681683:ios:f1f51a91bdd5e8f5c80e66',
    messagingSenderId: '105947681683',
    projectId: 'career-guidance-app-98f12',
    storageBucket: 'career-guidance-app-98f12.firebasestorage.app',
    iosBundleId: 'com.example.careerGuidanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu4il-68xX38EfTSR_Eati6kypYbXqnMQ',
    appId: '1:105947681683:ios:f1f51a91bdd5e8f5c80e66',
    messagingSenderId: '105947681683',
    projectId: 'career-guidance-app-98f12',
    storageBucket: 'career-guidance-app-98f12.firebasestorage.app',
    iosBundleId: 'com.example.careerGuidanceApp',
  );
}
